version: '3.9'

services:
  database:
    image: postgres:alpine
    container_name: imobiliaria_postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: imobdb
    volumes:
      - .data/:/var/lib/postgresql/data
    ports:
      - 5430:5432
